### ISSUE TITLE
Back to React.FunctionalComponent?

### ISSUE THREAD

**Issue by httpete** [eps1lon/types-react-codemod#101]
I jumped on the bandwagon to abandon React.FC, but now they have dropped the implicit children issue, so I feel that React.FunctionalComponent is the best way to type a React function. This mod must be easy for those who know this no? I want to go from:

```
export const Hello = ({
  treeID = 'testTreeID',
  counter = 0,
}: HelloProps): ReactElement => {
  return (
      <HelloCmp />
  );
};
```
to

```
export const Hello = FunctionalComponent<HelloProps> = 
```
and remove the :HelloProps from the props, and the return type of ReactElement and add:

```
import { type FunctionalComponent } from 'react';

**Comment by eps1lon** [comment]
So far the published codemods focus on migration efforts. I'm not yet sure if there's room for codemods applying other fixes but I'll definitely don't want to collect stylistic preferences. 

I would recommend publishing your own set of codemods if you wish to use such a codemod. Thanks for the suggestion!
