### ISSUE TITLE
Defective implicit children codemod

### ISSUE THREAD

**Issue by ravi-github** [eps1lon/types-react-codemod#300]
Sebastian, 

The implicit children codemod has the following defects . Any workarounds you can suggest ? 

- We have a repo with 1000's of components . The codemod adds children to all components whether it should really have children or not . We have only 10% of the components in our repo with children and 90% without any children. 

- Our codebase still heavily uses class components whereas the codemod works only for functional components

**Comment by eps1lon** [comment]
> The codemod adds children to all components whether it should really have children or not .

The codemod is intended to ease migration, not for correctness. If you want to stop relying on implicit, children, do not use this codemod.

>Our codebase still heavily uses class components whereas the codemod works only for functional components

Class components did not have implicit children
