### ISSUE TITLE
window.d.ts Transformation error ('export declare' must be followed by an ambient declaration.

### ISSUE THREAD

**Issue by mildfuzz** [eps1lon/types-react-codemod#309]
I see the following error:
```sh
window.d.ts Transformation error ('export declare' must be followed by an ambient declaration.
```

`window.ds.ts` looks like
```ts
export declare global {
  interface Window {
    globalThingMyAppNeeds: MyType<unknown>
  }
}
```

**Comment by eps1lon** [comment]
This looks like a legit error since TypeScript playground is also complaining here. Can you live without the `export` keyword?

```ts 
declare global {
  interface Window {
    globalThingMyAppNeeds: MyType<unknown>
  }
}
```

**Comment by mildfuzz** [comment]
yeah, I do need the export. I get a bunch of build failures. Typescript doesn't seem to pick up the changes to the window object without it

**Comment by eps1lon** [comment]
Closing since this seems to be an issue with TypeScript. `export declare global {}` is not valid.
