### ISSUE TITLE
Support Node.js v22

### ISSUE THREAD

**Issue by jerone** [eps1lon/types-react-codemod#446]
When installing `types-react-codemod` on Node.js v22 it will force install version 1.3.0 of the tool.

```
npx types-react-codemod --version
1.3.0
```

Only after forcing the latest version I get the latest released version, but with an unsupported engine message:

```
npx types-react-codemod@latest --version
Need to install the following packages:
types-react-codemod@3.4.1
Ok to proceed? (y)

npm warn EBADENGINE Unsupported engine {
npm warn EBADENGINE   package: 'types-react-codemod@3.4.1',
npm warn EBADENGINE   required: { node: '18.x || 20.x' },
npm warn EBADENGINE   current: { node: 'v22.6.0', npm: '10.9.1' }
npm warn EBADENGINE }

3.4.1
```

Node.js release 22.x is an official LTS: https://github.com/nodejs/release#release-schedule

---

There is also an discrepant of supported Node.js versions between the [documentation](https://github.com/eps1lon/types-react-codemod?tab=readme-ov-file#supported-platforms) and the [package.json](https://github.com/eps1lon/types-react-codemod/blob/c4304e0ab9d8c5f47f31e2086266ab5d944594b3/package.json#L15). Node.js v16 seems to be [dropped a while ago](https://github.com/eps1lon/types-react-codemod/pull/313).

**Comment by eps1lon** [comment]
> When installing types-react-codemod on Node.js v22 it will force install version 1.3.0 of the tool.


This is the default behavior of `npx`. It aggressively caches the resolved versions. Using `@latest` with `npx` will ensure the latest version is always used.

Support for Node.js 22.x will be added in https://github.com/eps1lon/types-react-codemod/pull/448
