### ISSUE TITLE
Import error

### ISSUE THREAD

**Issue by macnaughton** [eps1lon/types-react-codemod#68]
I received the following error when running the codemod:

```
/Users/..../..../node_modules/types-react-codemod/transforms/preset-18.js:1
import contextAnyTransform from "./context-any";
^^^^^^

SyntaxError: Cannot use import statement outside a module
```

Command run was ```npx types-react-codemod preset-18 ./src ```

This is using nodejs 16.

FYI, Downgrading to 1.1.0 resolved it.  Maybe related to #63 since the import in question is [preset-18](https://github.com/eps1lon/types-react-codemod/blob/main/transforms/preset-18.js)

**Comment by zachhardesty7** [comment]
Can confirm I experienced the same thing with Node v12 & v16 and running `1.1.0` worked for me
