### ISSUE TITLE
Implement `implicit-children`

### ISSUE THREAD

**Issue by eps1lon** [eps1lon/types-react-codemod#8]
Implementation suggestion 1:

Wrap type parameter of `FunctionComponent` (`FC`, `SFC`, `StatelessComponent` so that we guard against codemods for deprecated types being applied after this codemod) with `PropsWithChildren`.
If no type parameter is found add `PropsWithChildren<{}>` as type parameter.

Adding extraenous `children` is not considered a false-positive since type-coverage remains the same. Checking additions may be helpful to understand why implicit children were problematic.

**Comment by eps1lon** [comment]
Closed in https://github.com/eps1lon/types-react-codemod/pull/11

**Comment by Ayc0** [comment]
Shouldn't this be also be applied to `class MyCustomComponent extends React.Component<MyCustomComponentProps>`?
