### ISSUE TITLE
Issue with types on React.Children.map()

### ISSUE THREAD

**Issue by markmendozadev** [eps1lon/types-react-codemod#97]
```
interface ChildrenProps {
 children: React.ReactNode;
}
const Component = ({ children}: ChildrenProps) => {
 {React.Children.map(children, (child: React.ReactElement, i) => {
 }
```
I'm getting an error with children inside React.Children.map() when i use React.ReactNode
```
Argument of type 'ReactNode' is not assignable to parameter of type 'ReactElement<any, string | JSXElementConstructor<any>> | readonly ReactElement<any, string | JSXElementConstructor<any>>[]'.ts(2345)
```

but when I use children: JSX.Element[] | JSX.Element; as type, it doesn't. I'm still new to typescript and react and I couldn't find any answers as I search perhaps my keywords are wrong but if you guys are free can you help me understand why JSX. The element would work but not ReactNode? Anything can be assigned with React Node right? but I can't assign ReactNode to ReactElement?

**Comment by eps1lon** [comment]
`React.Children.map` will iterate over children which aren't necessarily ReactElement but all ReactNode (e.g. `string`). If you're sure these are elements and don't want static type checking, use type casting:

```tsx
import * as React from 'react'

interface ChildrenProps {
    children: React.ReactNode;
}
const Component = ({ children }: ChildrenProps) => {
    React.Children.map(children, (child) => {
        const element = child as React.ReactElement

        return element
    })
 }
```

[Playground Link](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAKjgQwM5wEoFNkGN4BmUEIcA5FDvmQFA3AB2MWUBeWcAwgBbAA2AE0oMACsTDoA3jTiy4uXoOEAuTFRgA6bHhgA5CAKwBuGgF8auCA1TxOJSAyxM4AXjgAKSfMVCncU6o8-L6i4qgAlK4AfHDScmo6GkFKThogyGDuCsHCADQe2YKRLjFx8XKW1vBYfFggTvBuhQIo6Nr4WuoAorX1THTlcpQwAK5QDHA1dQ0ycqbhMqZAA)
